# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='waiting_list',
            field=models.BooleanField(default=False),
        ),
    ]
